steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    gcloud compute ssh your-instance-name --zone=your-zone --project=your-project-id --command='ansible-playbook /mnt/data/ansible/playbook.yaml -i /mnt/data/ansible/inventory/gcp.yaml'